namespace AiLog.Contracts;

/// <summary>The grid-sized view of an <see cref="ExchangeLog"/>, served by the UI API and pushed over SSE.</summary>
public sealed class ExchangeSummary
{
    /// <summary>Log file name without extension.</summary>
    public required string Id { get; init; }

    /// <summary>Per-process counter that orders exchanges started in the same millisecond.</summary>
    public required long Sequence { get; init; }

    /// <summary>When ailog received the request.</summary>
    public required DateTimeOffset StartedAt { get; init; }

    /// <summary>HTTP method, e.g. "POST".</summary>
    public required string Method { get; init; }

    /// <summary>Route prefix (first path segment) that selected the upstream.</summary>
    public required string Route { get; init; }

    /// <summary>Request target with the route prefix stripped, e.g. "/v1/messages?beta=true".</summary>
    public required string Path { get; init; }

    /// <summary>Null when the upstream never answered.</summary>
    public int? StatusCode { get; init; }

    /// <summary>Wall-clock time from receiving the request to completion.</summary>
    public required double DurationMs { get; init; }

    /// <summary>How the exchange ended.</summary>
    public required ExchangeOutcome Outcome { get; init; }

    /// <summary>Request wire size (as sent, possibly compressed); 0 when there was no body.</summary>
    public required long RequestBytes { get; init; }

    /// <summary>Response wire size (as sent, possibly compressed); 0 when there was no body.</summary>
    public required long ResponseBytes { get; init; }

    /// <summary>Null when the response carried no recognisable usage block.</summary>
    public TokenUsage? Usage { get; init; }
}

/// <summary>Token counts normalised across providers.</summary>
public sealed class TokenUsage
{
    /// <summary>Total prompt tokens, including cache reads and cache writes.</summary>
    public long? InputTokens { get; init; }

    /// <summary>Tokens generated by the model.</summary>
    public long? OutputTokens { get; init; }

    /// <summary>Prompt tokens served from the provider's cache.</summary>
    public long? CacheReadTokens { get; init; }

    /// <summary>Prompt tokens written to the provider's cache.</summary>
    public long? CacheWriteTokens { get; init; }
}
